import styles from './Terms.module.scss';

export const PrivacyCookie = () => {
    return (
        <div className="container-fluid p-4" style={{
            margin: '0 auto',
            width: '65%',
            display: 'flex',
            flexDirection: 'column',
            marginTop: '8rem'
        }} >
            <span>Effective:  May 1, 2024</span>
            <h1 className={styles.h1}>Privacy Policy and Cookies Statement</h1>
            <p>
                Sync Remote LLC, hereinafter referred to as "Sync", “Sync Club” or "we," is the lawful proprietor and operator of a software platform designed to offer a wide range of services tailored to the needs of its members (the “Services”).
                <br /> <br />
                The services rendered encompass a breadth of functionalities, including, but not confined to, the facilitation of individual financial management. Such functionalities entail the provision of bespoke insights and recommendations derived from credit behavior analysis, alongside the facilitation of member interactions through chat mechanisms and exclusive rewards initiatives. Sync Club endeavors to cultivate an environment conducive to financial awareness and build good credit habits. Through an evaluation of members' interaction with our platform, including the linking of credit card accounts and demonstration of commendable credit conduct, selected members are granted access to a diverse array of benefits customized to align with their individual needs and preferences.For the purposes of this Agreement, the terms "you" and "your" shall collectively refer to the Users of Sync, encompassing both individual users and businesses alike.
                <br /> <br />
                The term "Content" shall include any information, text, links, graphics, photos, audio, videos, data, code, location tracking, financial information or other materials or arrangements of materials that are accessible for viewing, accessing, or interacting with through the Services.
                <br /> <br />
                This document constitutes our official Statement, providing comprehensive information on the collection, utilization, and management of your personal information. Our objective is to ensure utmost clarity and comprehension. It additionally outlines your rights, the appropriate manner of exercising them, and methods of contacting our organization. We kindly request your thorough review of this Statement, as it elucidates our practices concerning information and privacy. By accessing our websites, applications, and affiliated social media platforms, inclusive of computer, phone, tablet, or similar electronic devices (collectively referred to as "Devices"), you acknowledge and confirm that you have perused and comprehended the contents of this Statement.
            </p>
            <h2>Information we collect and process</h2>
            <p>
                By using our Services, we collect and process information from and about you. The type of information we collect depends on the kind of services that you are accessing. We gather certain information in different ways. Some of it is collected automatically when you interact with our servers or through cookies and similar tracking technologies. We also collect information from various sources, including you, business partners, and independent third-party sources. If you access our Services by clicking on a link from another website or use our Services to visit third-party websites, those websites may share information with us about how you use their services. The information we may collect encompasses a range of data points, including but not limited to: your name, age, gender, phone number, email address, physical address, geolocation, preferences, photographs, reviews, videos, device information (such as IP address, browser type, connection characteristics, device specifications, etc.), online activity, historical records of interactions with our Services, billing details, payment information, and information obtained from third-party entities for the purpose of social media login. Furthermore, we acquire location information when your Device transmits such data to us.
                <br /> <br />
                For the businesses registered in our platform, as part of our business operations we collect pertinent data that we believe will facilitate the provision of our Services. Such information may comprise the price, products, number of sales, discounts or other information included to faciliatate the Services. For the purposes of this agreement, the term "Information" shall encompass all of the data points mentioned above.
            </p>
            <h2>Information Uses and Purposes</h2>
            <p>
                Sync utilizes the Information for the primary objective of delivering the Services in an efficient and effective manner. This includes but is not limited to enhancing the functionality and usability of our Services, tailoring them to meet individual preferences and requirements, facilitating seamless communication between users and stakeholders, as well as ensuring compliance with applicable legal obligations and regulations. We reserve the right to amalgamate data from various sources to enrich our comprehension and tailor our offerings to align with your preferences. Furthermore, we may employ the Information for marketing and promotional purposes, such as informing users about new features, updates, or relevant offers that may be of interest to them. This enables us to personalize user experiences, provide targeted recommendations, and optimize the overall user engagement with our Services.
                <br /> <br />
                We collect various types of information from you to provide and improve our services, including: (1)Personal Information: When you sign up for Sync Club, we may collect personal information such as your name, email address, phone number, Social Security Number (SSN), and other identifying information necessary to verify your identity and provide our services. (2) Financial Information: If you choose to link your credit card account with Sync Club, we may collect transaction data and other financial information to deliver personalized recommendations and notifications. (3) User Preferences: We may collect information about your interests, preferences, and communication preferences to tailor your experience on Sync Club and provide relevant content and offers. (4) Interaction Data: We may collect information about your interactions and usage patterns with Sync Club to improve our Services and personalize your experience.
                <br /> <br />
                The Information is instrumental in enabling us to personalize user experiences, optimize the performance of our Services, and maintain transparency and accountability in our operations. Additionally, we may employ the Information for the purposes of legal compliance, risk management, dispute resolution, and the enforcement of rights and obligations as outlined in our contractual agreements and governing laws. By utilizing the Information in this manner, we strive to uphold the integrity of our Services and provide users with a secure and satisfactory experience. Rest assured that any marketing or promotional activities involving the Information will be conducted in accordance with applicable laws and regulations, as well as industry best practices to protect user privacy and ensure compliance with relevant consent requirements.
                <br /> <br />
                Sync Remote LLC respects the privacy and safety of individuals under the age of 13 and does not knowingly collect their information. We reserve the right, at our sole discretion, to deny access to the Services to anyone, at any time, and for any reason, including violations of this Agreement. We also reserve the right to take steps to verify your identity and Right to deny access to anyone.
            </p>
            <h2>Information sharing</h2>
            <p>In accordance with our privacy practices, we reserve the right to disclose the Information to select entities, including but not limited to suppliers, business partners, social media websites, advertising networks, fraud detection companies, and other third parties. This sharing of Information is conducted within the parameters defined by applicable laws and regulations, and it serves various purposes aimed at optimizing our Services and promoting a seamless user experience. It is important to note that we undertake reasonable measures to ensure that any sharing of Information is done in a manner consistent with legal requirements and industry standards to safeguard user privacy and maintain data security.</p>
            <h2>Information choices</h2>
            <p>
                In your user profile, you have options over the processing and use of your information. This includes the option to specify preferences regarding the manner in which we communicate with you, and other related aspects. We acknowledge and respect your right to make these choices, and we strive to provide a user-friendly interface that allows you to manage these preferences according to your individual needs and preferences. By utilizing the options available in your user profile, you can customize and tailor the processing and use of your information to align with your specific requirements. Additionally, if you ever want to close your account, you can do so easily by accessing your user profile settings. Just keep in mind that if you choose to close your account, we'll deactivate it and make sure your profile information is no longer visible to others. However, it's worth mentioning that we may retain some information related to your account, like past transactions, for internal use. This includes purposes such as backups, fraud prevention, dispute resolution, investigations, our own legitimate business interests, and compliance with legal requirements. We'll keep this information for as long as it's necessary to fulfill the purposes stated in this Statement.
                <br /> <br />
                Sync complies with the Gramm-Leach-Bliley Act (GLBA) and provides users with clear information before obtaining consent for accessing financial information. Users have the right to revoke authorization and control the use of their data.</p>
            <h2>Data security</h2>
            <p>
                Sync diligently implements reasonable measures to safeguard the Information. Nevertheless, it is important to acknowledge that despite our best efforts, we cannot provide an absolute guarantee of the security of information against unauthorized access, use, or disclosure. Factors beyond our control, such as unauthorized entry or use, hardware or software failure, or other unforeseen circumstances, may compromise the security and confidentiality of the information. We strive to adopt industry-standard security practices and regularly update our systems to mitigate potential risks. However, users should be aware that the transmission and storage of information over the internet inherently involve certain risks, and it is advisable to exercise caution when sharing sensitive or confidential information through our Services. In the event of a data breach concerning member information, Sync Club will promptly notify affected individuals via email, as soon as practicable and deemed safe by Sync Club's discretion.
            </p>
            <h2>Cookies statement</h2>
            <p>
                In our commitment to provide you with a seamless and valuable experience while accessing our Services, we employ cookies and similar technologies to enhance browsing efficiency, fortify website security, and deliver targeted advertising. These cookies, which are small text files placed on your Device during your visit to almost any website, store essential information pertaining to your internet usage. Subsequently, when you revisit the website, your browser transmits this information back, facilitating recognition of your Device and the provision of personalized content. Furthermore, we utilize additional tracking technologies such as pixels, SDKs, or server logs, which perform similar functions. Cookies and tracking technologies are instrumental in remembering your login details and streamlining your preferences.
            </p>
            <h2>Policy changes</h2>
            <p>
                We reserve the right to modify this Statement in the future. By continuing to access or use the Services after such changes, you indicate your acceptance of the updated Statement. Registered users of our Services, referred to as "Account Holders," will be notified of significant changes to these statements either through email sent to the associated account or by displaying a notice on our websites.
            </p>
            <h2>Contact</h2>
            <p>
                For any inquiries or assistance that we may be able to provide, please contact us via mail at the following address: 17 Allston Street #2, Allston, MA 02134, USA.
                <br /> <br />
                For supplementary information on users from California, Nevada, Virginia, Colorado, and Connecticut please check the following <a href="/terms/privacy-notice">Privacy Notice</a>.
            </p>
        </div>
    )
}